### PR TITLE
Don't hardcode the 'type' as bundle field

### PR DESCRIPTION
**Pull request by dawehner**

### CODE REVIEW

**Comment by bdragon28** [comment]
Err, this doesn't actually work.

**Comment by bdragon28** [comment]
Here's one that doesn't actually crash... Thoughts?

``` diff
diff --git a/src/Entity/Form/EntityBaseForm.php b/src/Entity/Form/EntityBaseForm.php
index 661898a..8be9cfd 100644
--- a/src/Entity/Form/EntityBaseForm.php
+++ b/src/Entity/Form/EntityBaseForm.php
@@ -28,7 +28,7 @@ class EntityBaseForm extends ContentEntityForm {
     parent::prepareEntity();

     /** @var EntityTypeBaseInterface $entity_type */
-    $entity_type = $this->entity->type->referencedEntities()[0];
+    $entity_type = $this->entity->{$this->entity->getEntityType()->getKey('bundle')}->referencedEntities()[0];

     // Set up default values, if required.
     if (!$this->entity->isNew()) {
@@ -110,7 +110,7 @@ class EntityBaseForm extends ContentEntityForm {
    */
   public function save(array $form, FormStateInterface $form_state) {
     /** @var EntityTypeBaseInterface $entity_type */
-    $entities = $this->entity->type->referencedEntities();
+    $entities = $this->entity->{$this->entity->getEntityType()->getKey('bundle')}->referencedEntities();
     $entity_type = reset($entities);

     // Save as a new revision if requested to do so.
```

**Comment by andypost** [comment]
This should actually check that entity has bundles

**Comment by bdragon28** [comment]
Given that this is EntityBaseForm and not EntityTypeBaseForm, how do we get to this form without having bundles exactly? (serious question, if I am misunderstanding the design here I'd really like to know)

**Comment by Jaesin** [comment]
See [bundle-fix commit](https://github.com/Jaesin/content_entity_base/commit/b9fe57a4f4ff7b6afafc4ec3c9c6347c699581d9)

**Comment by dawehner** [comment]
@Jaesin Works for me. Let's merge it!

**Comment by Jaesin** [comment]
Already fixed by #28.

**Pull request closed without merging**
